---
title: "pitchfork-reviews"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(RSQLite)
library(odbc)
library(glue)

theme_set(theme_bw())

#define file path to database
rawPath <- "./rawData/"

#define connection to local database
con <- dbConnect(RSQLite::SQLite(), paste0(rawPath, "database.sqlite"))

#db consists of 6 tables: artists, content, genre, labels, reviews, and years
#they all share a common key: reviewid
dbListTables(con) %>% map(~dbListFields(conn = con, .x))

dbListTables(con) %>% map(~tbl(con, .x) %>% head)

#let's try and mash it all together - except the content
dbGetQuery(conn = con,
           "select a.*, b.artist
           from reviews as a
           left join artists as b
           on a.reviewid = b.reviewid
           ")

pitchfork_reviews <- tbl_df(tbl(con, "reviews") %>%
                        left_join(tbl(con, "genres"), by = c("reviewid")) %>%
                        left_join(tbl(con, "labels"), by = c("reviewid")) %>%
                        #left_join(tbl(con, "years"), by = c("reviewid")) %>% we drop the years join because this is linked to the difference between review date and the date the album was published - who cares?
                        left_join(tbl(con, "content"), by = c("reviewid"))) %>%
                        distinct()

#we find that we get duplicates related to multiple genres + record labels
#so we use glue collapse to combine them all
genres <- pitchfork_reviews %>% distinct(reviewid, genre) %>%
                      group_by(reviewid) %>%
                      summarise(genre = glue_collapse(genre, sep = " ; ")) %>%
                      ungroup()

labels <- pitchfork_reviews %>% distinct(reviewid, label) %>%
                      group_by(reviewid) %>%
                      summarise(label = glue_collapse(label, "  ; ")) %>%
                      ungroup()

#and recombine with the rest of the data
clean_pitchfork_reviews <- pitchfork_reviews %>% select(-genre, -label) %>% 
                           distinct() %>%
                           left_join(genres, by = c("reviewid")) %>%
                           left_join(labels, by = c("reviewid"))

```


```{r}
#eda

#reviews over time
clean_pitchfork_reviews %>% count(pub_year) %>%
                            ggplot(aes(x = pub_year, y = n)) +
                            geom_line()

#top 25 artists by number of reviews - excludes various artists
clean_pitchfork_reviews %>% filter(artist != "various artists") %>%
                            count(artist, sort = T) %>%
                            head(25) %>%
                            mutate(artist = str_to_title(artist),
                                   artist = fct_reorder(artist, n)) %>%
                            ggplot(aes(x = artist, y = n)) +
                            geom_col(aes(fill = artist), show.legend = FALSE) + 
                            coord_flip() +
                            labs(x = "",
                                 y = "Number of reviews",
                              title = "Which artists have the most reviews on Pitchfork?",
                                 subtitle = "Excludes 'Various Artists'")

#what are the average review scores by genre?
#normally distributed so we stick to the mean
clean_pitchfork_reviews %>% group_by(genre) %>%
                            summarise(numReviews = n(),
                                      meanScore = mean(score),
                                      sdScore = sd(score)) %>%
                            arrange(desc(numReviews)) %>% 
                            head(16) %>%
                            mutate(genre = replace_na(genre, "No genre listed"),
                                   genre = fct_reorder(genre, meanScore)) %>%
                            ggplot(aes(x = genre, y = meanScore)) +
                            geom_point() +
                            geom_errorbar(aes(ymin = meanScore - sdScore,
                                              ymax = meanScore + sdScore)) +
                            coord_flip() +
                            labs(x = "",
                                 y = "Mean Review Score",
                      title = "Which genre had the highest average score on Pitchfork?")



```

